[package]
name = "aes"
version = "0.8.3"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "AES library for Xous"

# Dependency versions enforced by Cargo.lock.
[dependencies]
cipher = "0.4.2"
zeroize = { version = "1.6.0", optional = true, default_features = false }

[features]
hazmat = []  # Expose cryptographically hazardous APIs
default = []
